// =============================================================================
// Theme Colors - Auto-generated by init script
// =============================================================================
// NOTE: In Tailwind v4, colors are defined in globals.css @theme block.
// This file exists for reference and TypeScript types only.

export const colorReference = {
  primary: {
    "50": "#F1FDFB",
    "100": "#E3FCF7",
    "200": "#BDFAEE",
    "300": "#81F8E2",
    "400": "#42FAD8",
    "500": "#00C29E",
    "600": "#00D6AE",
    "700": "#00AD8D",
    "800": "#00856C",
    "900": "#005C4B",
    "950": "#00332A",
    DEFAULT: "#00C29E",
  },
  secondary: {
    "50": "#F4FAFA",
    "100": "#E9F6F6",
    "200": "#CAEDEC",
    "300": "#99E0DF",
    "400": "#65D7D5",
    "500": "#114C4B",
    "600": "#25B1AF",
    "700": "#1C918F",
    "800": "#14706F",
    "900": "#0D4F4E",
    "950": "#072C2B",
    DEFAULT: "#114C4B",
  },
  accent: {
    "50": "#FDF4F1",
    "100": "#FCE8E3",
    "200": "#FAC8BD",
    "300": "#F89681",
    "400": "#FA6342",
    "500": "#FF5733",
    "600": "#D62600",
    "700": "#AD1F00",
    "800": "#851700",
    "900": "#5C1000",
    "950": "#330900",
    DEFAULT: "#FF5733",
  },
  neutral: {
    "50": "#F7F7F7",
    "100": "#F0F0F0",
    "200": "#DBDBDB",
    "300": "#BDBDBD",
    "400": "#9E9E9E",
    "500": "#71717A",
    "600": "#656571",
    "700": "#50505D",
    "800": "#3C3C49",
    "900": "#282833",
    "950": "#16161D",
    DEFAULT: "#71717A",
  },
  success: {
    "50": "#F3FCF9",
    "100": "#E6FAF3",
    "200": "#C3F4E4",
    "300": "#8CEECD",
    "400": "#51EBB8",
    "500": "#10B981",
    "600": "#0FC78A",
    "700": "#0AA370",
    "800": "#077E56",
    "900": "#04583C",
    "950": "#023122",
    DEFAULT: "#10B981",
  },
  warning: {
    "50": "#FDFAF2",
    "100": "#FBF5E4",
    "200": "#F8E8BE",
    "300": "#F6D683",
    "400": "#F7C546",
    "500": "#FBBF24",
    "600": "#D49A02",
    "700": "#AD7D00",
    "800": "#856000",
    "900": "#5C4200",
    "950": "#332500",
    DEFAULT: "#FBBF24",
  },
  error: {
    "50": "#FCF3F3",
    "100": "#FAE6E6",
    "200": "#F4C3C3",
    "300": "#EE8B8B",
    "400": "#EB5151",
    "500": "#EF4444",
    "600": "#C70F0F",
    "700": "#A30A0A",
    "800": "#7E0606",
    "900": "#580404",
    "950": "#310202",
    DEFAULT: "#EF4444",
  },
  info: {
    "50": "#F2F6FD",
    "100": "#E5EDFB",
    "200": "#C0D5F7",
    "300": "#87B0F3",
    "400": "#4B8AF2",
    "500": "#3B82F6",
    "600": "#0753CF",
    "700": "#0443A9",
    "800": "#023383",
    "900": "#00235B",
    "950": "#001333",
    DEFAULT: "#3B82F6",
  },

  foreground: "#001A1A",
  background: "#FFFFFF",
  muted: "#F0F0F0",
  gold: "#FFC72C",

  white: "#FFFFFF",
  black: "#000000",
  transparent: "transparent",
} as const;

export type ThemeColors = typeof colorReference;
export type ColorScale = typeof colorReference.primary;

export const alpha = (hex: string, a: number): string =>
  hex +
  Math.round(Math.min(1, Math.max(0, a)) * 255)
    .toString(16)
    .padStart(2, "0")
    .toUpperCase();

export const rgba = (hex: string, a: number): string => {
  const int = parseInt(hex.replace("#", ""), 16);
  return `rgba(${(int >> 16) & 255}, ${(int >> 8) & 255}, ${int & 255}, ${a})`;
};

export const semanticColors = {
  light: {
    background: colorReference.white,
    foreground: colorReference.foreground,
    card: colorReference.white,
    cardForeground: colorReference.foreground,
    primary: colorReference.primary.DEFAULT,
    primaryForeground: colorReference.primary[950],
    secondary: colorReference.secondary.DEFAULT,
    secondaryForeground: colorReference.white,
    muted: colorReference.neutral[100],
    mutedForeground: colorReference.neutral[600],
    accent: colorReference.neutral[100],
    accentForeground: colorReference.foreground,
    border: colorReference.neutral[200],
    ring: colorReference.primary.DEFAULT,
  },
  dark: {
    background: colorReference.foreground,
    foreground: colorReference.neutral[50],
    card: colorReference.secondary[950],
    cardForeground: colorReference.neutral[50],
    primary: colorReference.primary.DEFAULT,
    primaryForeground: colorReference.primary[950],
    secondary: colorReference.secondary[800],
    secondaryForeground: colorReference.white,
    muted: colorReference.secondary[950],
    mutedForeground: colorReference.neutral[300],
    accent: colorReference.secondary[800],
    accentForeground: colorReference.neutral[50],
    border: colorReference.secondary[800],
    ring: colorReference.primary.DEFAULT,
  },
} as const;
