import type {Metadata} from "next";
import {Geist, Geist_Mono, Lora, Outfit} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";

const outfitHeading = Outfit({subsets: ['latin'], variable: '--font-heading'});
const lora = Lora({subsets: ['latin'], variable: '--font-serif'});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
    return (
        <html lang="en">
        <body
            className={cn(geistSans.variable, geistMono.variable, "font-serif", lora.variable, outfitHeading.variable)}>
        {/* TODO: providers */}
        {children}
        </body>
        </html>
    );
}
