/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    categories: Category;
    users: User;
    faqs: Faq;
    'email-templates': EmailTemplate;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('sk' | 'en') | ('sk' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'sk' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Used to determine the order of FAQs
   */
  sortOrder?: number | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: string;
  name: string;
  description?: string | null;
  subject: string;
  title?: string | null;
  /**
   * Please input only one font family here.
   */
  fontFamily: string[];
  fallbackFontFamily: (
    | 'Arial'
    | 'Helvetica'
    | 'Verdana'
    | 'Georgia'
    | 'Times New Roman'
    | 'serif'
    | 'sans-serif'
    | 'monospace'
    | 'cursive'
    | 'fantasy'
  )[];
  webFont?: {
    url?: string | null;
    format?: ('woff' | 'woff2' | 'truetype' | 'opentype' | 'embedded-opentype' | 'svg') | null;
  };
  fontWeight?: string | null;
  fontStyle?: string | null;
  /**
   * The body of the email template. Related to the main content.
   */
  body?: ReactEmailContainerBlock[] | null;
  /**
   * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
   */
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailContainerBlock".
 */
export interface ReactEmailContainerBlock {
  content?:
    | (
        | ReactEmailSectionBlock
        | ReactEmailRowBlock
        | ReactEmailHeadingBlock
        | ReactEmailButtonBlock
        | ReactEmailHrBlock
        | ReactEmailImageBlock
        | ReactEmailTextBlock
        | ReactEmailLinkBlock
        | ReactEmailSpacerBlock
        | MacroBlock
      )[]
    | null;
  /**
   * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
   */
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'container';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailSectionBlock".
 */
export interface ReactEmailSectionBlock {
  content?:
    | (
        | ReactEmailRowBlock
        | ReactEmailHeadingBlock
        | ReactEmailImageBlock
        | ReactEmailButtonBlock
        | ReactEmailTextBlock
        | ReactEmailLinkBlock
        | ReactEmailHrBlock
        | ReactEmailSpacerBlock
        | MacroBlock
      )[]
    | null;
  /**
   * CSS color value (e.g., #ffffff, rgba(255,255,255,0.9))
   */
  backgroundColor?: string | null;
  padding?: ('0' | '16px' | '32px' | '48px') | null;
  /**
   * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
   */
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailRowBlock".
 */
export interface ReactEmailRowBlock {
  columns?:
    | {
        content?:
          | (
              | ReactEmailTextBlock
              | ReactEmailButtonBlock
              | ReactEmailHeadingBlock
              | ReactEmailImageBlock
              | ReactEmailLinkBlock
              | ReactEmailSpacerBlock
              | MacroBlock
            )[]
          | null;
        width?: ('1/4' | '1/3' | '1/2' | '2/3' | '3/4' | 'full') | null;
        align?: ('left' | 'center' | 'right') | null;
        verticalAlign?: ('top' | 'middle' | 'bottom') | null;
        /**
         * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
         */
        style?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
   */
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'row';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailTextBlock".
 */
export interface ReactEmailTextBlock {
  content: (ReactEmailLinkBlock | ReactEmailPlainTextBlock | MacroBlock)[];
  fontSize?: ('0.75rem' | '0.875rem' | '1rem' | '1.125rem' | '1.25rem') | null;
  textAlign?: ('left' | 'center' | 'right') | null;
  color?: string | null;
  lineHeight?: ('1.2' | '1.4' | '1.6' | '1.8') | null;
  /**
   * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
   */
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailLinkBlock".
 */
export interface ReactEmailLinkBlock {
  text: string;
  url: string;
  target?: ('_self' | '_blank') | null;
  color?: string | null;
  underline?: boolean | null;
  /**
   * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
   */
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'link';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailPlainTextBlock".
 */
export interface ReactEmailPlainTextBlock {
  content: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'plainText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MacroBlock".
 */
export interface MacroBlock {
  type: 'variable' | 'condition' | 'loop' | 'function' | 'date' | 'config';
  /**
   * Variable name to inject (e.g., firstName, company)
   */
  variable?: string | null;
  condition?: {
    /**
     * Condition expression (e.g., isPremium, hasDiscount)
     */
    expression: string;
    /**
     * Content to show when condition is true
     */
    trueContent?: ReactEmailPlainTextBlock[] | null;
    /**
     * Content to show when condition is false
     */
    falseContent?: ReactEmailPlainTextBlock[] | null;
  };
  loop?: {
    /**
     * Collection to iterate over (e.g., items, products)
     */
    collection: string;
    /**
     * Variable name for each item in the loop
     */
    itemName?: string | null;
    /**
     * Content to repeat for each item
     */
    content?: ReactEmailPlainTextBlock[] | null;
  };
  function?: {
    name: 'uppercase' | 'lowercase' | 'capitalize' | 'truncate' | 'formatNumber';
    /**
     * Variable or value to pass to the function
     */
    argument: string;
    /**
     * Additional options (e.g., length for truncate)
     */
    options?: string | null;
  };
  date?: {
    /**
     * Date format (e.g., YYYY-MM-DD, MM/DD/YYYY)
     */
    format?: string | null;
    /**
     * Show relative time (e.g., 2 days ago)
     */
    relative?: boolean | null;
  };
  config?: {
    /**
     * Configuration key to access (e.g., appName, supportEmail)
     */
    key: string;
    /**
     * Default value if config key is not found
     */
    fallback?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'macro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailButtonBlock".
 */
export interface ReactEmailButtonBlock {
  text: string;
  url: string;
  target?: ('_self' | '_blank') | null;
  variant?: ('primary' | 'secondary' | 'outline') | null;
  backgroundColor?: string | null;
  textColor?: string | null;
  borderRadius?: ('0px' | '4px' | '8px' | '16px' | '999px') | null;
  padding?: ('8px 16px' | '12px 24px' | '16px 32px') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
   */
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailHeadingBlock".
 */
export interface ReactEmailHeadingBlock {
  content: (ReactEmailLinkBlock | ReactEmailPlainTextBlock | MacroBlock)[];
  level?: ('h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6') | null;
  textAlign?: ('left' | 'center' | 'right') | null;
  /**
   * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
   */
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailImageBlock".
 */
export interface ReactEmailImageBlock {
  /**
   * The image to display in the email template.
   */
  image?: (string | null) | Media;
  alt?: string | null;
  /**
   * Width in pixels, leave empty for auto
   */
  width?: number | null;
  /**
   * Height in pixels, leave empty for auto
   */
  height?: number | null;
  objectFit?: ('cover' | 'contain') | null;
  align?: ('left' | 'center' | 'right') | null;
  /**
   * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
   */
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailSpacerBlock".
 */
export interface ReactEmailSpacerBlock {
  height?: ('8px' | '16px' | '24px' | '32px' | '48px' | '64px') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailHrBlock".
 */
export interface ReactEmailHrBlock {
  color?: string | null;
  thickness?: ('1px' | '2px' | '3px') | null;
  margin?: ('16px 0' | '32px 0' | '48px 0') | null;
  /**
   * Additional custom style object to override the default styles, e.g. { "backgroundColor": "#333" }
   */
  style?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hr';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: string;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  locale?: ('all' | 'sk' | 'en') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: string;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: string | EmailTemplate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  sortOrder?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  subject?: T;
  title?: T;
  fontFamily?: T;
  fallbackFontFamily?: T;
  webFont?:
    | T
    | {
        url?: T;
        format?: T;
      };
  fontWeight?: T;
  fontStyle?: T;
  body?:
    | T
    | {
        container?: T | ReactEmailContainerBlockSelect<T>;
      };
  style?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailContainerBlock_select".
 */
export interface ReactEmailContainerBlockSelect<T extends boolean = true> {
  content?:
    | T
    | {
        section?: T | ReactEmailSectionBlockSelect<T>;
        row?: T | ReactEmailRowBlockSelect<T>;
        heading?: T | ReactEmailHeadingBlockSelect<T>;
        button?: T | ReactEmailButtonBlockSelect<T>;
        hr?: T | ReactEmailHrBlockSelect<T>;
        image?: T | ReactEmailImageBlockSelect<T>;
        text?: T | ReactEmailTextBlockSelect<T>;
        link?: T | ReactEmailLinkBlockSelect<T>;
        spacer?: T | ReactEmailSpacerBlockSelect<T>;
        macro?: T | MacroBlockSelect<T>;
      };
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailSectionBlock_select".
 */
export interface ReactEmailSectionBlockSelect<T extends boolean = true> {
  content?:
    | T
    | {
        row?: T | ReactEmailRowBlockSelect<T>;
        heading?: T | ReactEmailHeadingBlockSelect<T>;
        image?: T | ReactEmailImageBlockSelect<T>;
        button?: T | ReactEmailButtonBlockSelect<T>;
        text?: T | ReactEmailTextBlockSelect<T>;
        link?: T | ReactEmailLinkBlockSelect<T>;
        hr?: T | ReactEmailHrBlockSelect<T>;
        spacer?: T | ReactEmailSpacerBlockSelect<T>;
        macro?: T | MacroBlockSelect<T>;
      };
  backgroundColor?: T;
  padding?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailRowBlock_select".
 */
export interface ReactEmailRowBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        content?:
          | T
          | {
              text?: T | ReactEmailTextBlockSelect<T>;
              button?: T | ReactEmailButtonBlockSelect<T>;
              heading?: T | ReactEmailHeadingBlockSelect<T>;
              image?: T | ReactEmailImageBlockSelect<T>;
              link?: T | ReactEmailLinkBlockSelect<T>;
              spacer?: T | ReactEmailSpacerBlockSelect<T>;
              macro?: T | MacroBlockSelect<T>;
            };
        width?: T;
        align?: T;
        verticalAlign?: T;
        style?: T;
        id?: T;
      };
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailTextBlock_select".
 */
export interface ReactEmailTextBlockSelect<T extends boolean = true> {
  content?:
    | T
    | {
        link?: T | ReactEmailLinkBlockSelect<T>;
        plainText?: T | ReactEmailPlainTextBlockSelect<T>;
        macro?: T | MacroBlockSelect<T>;
      };
  fontSize?: T;
  textAlign?: T;
  color?: T;
  lineHeight?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailLinkBlock_select".
 */
export interface ReactEmailLinkBlockSelect<T extends boolean = true> {
  text?: T;
  url?: T;
  target?: T;
  color?: T;
  underline?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailPlainTextBlock_select".
 */
export interface ReactEmailPlainTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MacroBlock_select".
 */
export interface MacroBlockSelect<T extends boolean = true> {
  type?: T;
  variable?: T;
  condition?:
    | T
    | {
        expression?: T;
        trueContent?:
          | T
          | {
              plainText?: T | ReactEmailPlainTextBlockSelect<T>;
            };
        falseContent?:
          | T
          | {
              plainText?: T | ReactEmailPlainTextBlockSelect<T>;
            };
      };
  loop?:
    | T
    | {
        collection?: T;
        itemName?: T;
        content?:
          | T
          | {
              plainText?: T | ReactEmailPlainTextBlockSelect<T>;
            };
      };
  function?:
    | T
    | {
        name?: T;
        argument?: T;
        options?: T;
      };
  date?:
    | T
    | {
        format?: T;
        relative?: T;
      };
  config?:
    | T
    | {
        key?: T;
        fallback?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailButtonBlock_select".
 */
export interface ReactEmailButtonBlockSelect<T extends boolean = true> {
  text?: T;
  url?: T;
  target?: T;
  variant?: T;
  backgroundColor?: T;
  textColor?: T;
  borderRadius?: T;
  padding?: T;
  align?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailHeadingBlock_select".
 */
export interface ReactEmailHeadingBlockSelect<T extends boolean = true> {
  content?:
    | T
    | {
        link?: T | ReactEmailLinkBlockSelect<T>;
        plainText?: T | ReactEmailPlainTextBlockSelect<T>;
        macro?: T | MacroBlockSelect<T>;
      };
  level?: T;
  textAlign?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailImageBlock_select".
 */
export interface ReactEmailImageBlockSelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  width?: T;
  height?: T;
  objectFit?: T;
  align?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailSpacerBlock_select".
 */
export interface ReactEmailSpacerBlockSelect<T extends boolean = true> {
  height?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReactEmailHrBlock_select".
 */
export interface ReactEmailHrBlockSelect<T extends boolean = true> {
  color?: T;
  thickness?: T;
  margin?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug: 'media' | 'categories' | 'users' | 'faqs' | 'email-templates' | 'exports' | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}